start-at-login = true

after-startup-command = [
    'exec-and-forget borders active_color=0xff7dc4e4 inactive_color=0xff494d64 width=8.0',
]

# Ghostty tiling workaround
[[on-window-detected]]
if.app.id="com.mitchellh.ghostty"
run= [
    "layout tiling",
]
