#!/usr/bin/env bash
# ripped off https://github.com/jessarcher/dotfiles/blob/master/install

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# install homebrew if it's not already installed
if ! command -v brew &>/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle --file="$DOTFILES"/Brewfile

ln -sf "$DOTFILES"/zsh/zshrc "$HOME"/.zshrc

rm -rf "$HOME"/.tmux
ln -s "$DOTFILES"/tmux/.tmux "$HOME"/.tmux
ln -sf "$DOTFILES"/tmux/tmux.conf "$HOME"/.tmux.conf

rm -rf "$HOME"/Library/Application\ Support/com.mitchellh.ghostty/config
ln -s "$DOTFILES"/ghostty/config "$HOME"/Library/Application\ Support/com.mitchellh.ghostty/config

rm -rf "$HOME"/.config/aerospace
ln -s "$DOTFILES"/aerospace/aerospace.toml "$HOME"/.config/aerospace/aerospace.toml

rm -rf "$HOME"/.config/nvim
ln -s "$DOTFILES"/nvim "$HOME"/.config/nvim

rm -rf "$HOME"/.ideavimrc
ln -sf "$DOTFILES"/ideavim/.ideavimrc "$HOME"/.ideavimrc

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

ansible-playbook secrets/secrets.yml --ask-vault-pass
