#!/usr/bin/env bash
# ripped off https://github.com/jessarcher/dotfiles/blob/master/install

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

ln -sf "$DOTFILES"/zsh/zshrc "$HOME"/.zshrc

rm -rf "$HOME"/.tmux
ln -s "$DOTFILES"/tmux/.tmux "$HOME"/.tmux
ln -sf "$DOTFILES"/tmux/tmux.conf "$HOME"/.tmux.conf

rm -rf "$HOME"/.config/alacritty
ln -s "$DOTFILES"/alacritty "$HOME"/.config/alacritty

rm -rf "$HOME"/.config/nvim
ln -s "$DOTFILES"/nvim "$HOME"/.config/nvim

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
