#!/usr/bin/env bash
# ripped off https://github.com/jessarcher/dotfiles/blob/master/install

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

if ! command -v brew &>/dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

brew bundle --file="$DOTFILES"/Brewfile

ln -sf "$DOTFILES"/zsh/zshrc "$HOME"/.zshrc

rm -rf "$HOME"/.tmux
ln -s "$DOTFILES"/tmux/.tmux "$HOME"/.tmux
ln -sf "$DOTFILES"/tmux/tmux.conf "$HOME"/.tmux.conf

rm -rf "$HOME"/.config/kitty
ln -s "$DOTFILES"/kitty "$HOME"/.config/kitty

rm -rf "$HOME"/.config/nvim
ln -s "$DOTFILES"/nvim "$HOME"/.config/nvim

rm -rf "$HOME"/.ideavimrc
ln -sf "$DOTFILES"/ideavim/.ideavimrc "$HOME"/.ideavimrc

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

ansible-playbook secrets.yml --ask-vault-pass
