# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
# export PATH=/usr/local/Cellar/llvm/14.0.6/bin:$PATH
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH=$HOME/Development/flutter/bin:$PATH
export PATH=$HOME/bin:~/.composer/vendor/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"
export PATH=$HOME/Development/node-v18.7.0/bin:$PATH
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"
export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
export CC="/opt/homebrew/opt/llvm/bin/clang"
export XDG_CONFIG_HOME=$HOME/.config

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="jnrowe"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	artisan
	composer
	git
	z
	brew
	zsh-autosuggestions
	web-search
	dirhistory
	vi-mode
	emotty
	emoji
	fzf
	rust
	sudo
	tmux
	rbenv
	tmux
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR='vim'
else
	export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases

alias zshconfig="nvim ~/.dotfiles/zsh/zshrc"
alias ohmyzsh="cd ~/.oh-my-zsh"
alias hxconfig="hx ~/.config/helix/config.toml"
alias vi="nvim"
alias refrezsh="source ~/.zshrc"
alias myip="curl http://ipecho.net/plain; echo"
alias gitpretty="git log --all --decorate --oneline --graph"
alias oldbrew="arm /usr/local/bin/brew"
alias ls="lsd"
alias a="artisan"

nah() {
	git reset --hard
	git clean -df
	if [ -d ".git/rebase-apply" ] || [ -d ".git/rebase-merge" ]; then
		git rebase --abort
	fi
}

# zsh-autosuggest config
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=60'

# artisan default editor
# ARTISAN_OPEN_ON_MAKE_EDITOR=$EDITOR

# brew config
if [[ $(uname) != "Darwin" ]]; then
	eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

# for m1 mac

arm() {
	arch -x86_64 $@
}

# sound shit
export GIO_EXTRA_MODULES=/usr/lib/x86_64-linux-gnu/gio/modules/

# ruby
eval "$(rbenv init - zsh)"
#export GEM_PATH=/Users/jsellars/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
#export GEM_SPEC_CACHE=/Users/jsellars/.rbenv/versions/3.1.2/lib/ruby/gems/specs
export PATH="/opt/homebrew/opt/openssl@3/bin:$PATH"

eval $(thefuck --alias)

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Herd injected PHP 8.1 configuration.
export HERD_PHP_81_INI_SCAN_DIR="/Users/jsellars/Library/Application Support/Herd/config/php/81/"

# Herd injected PHP 8.2 configuration.
export HERD_PHP_82_INI_SCAN_DIR="/Users/jsellars/Library/Application Support/Herd/config/php/82/"

# Herd injected PHP binary.
export PATH="/Users/jsellars/Library/Application Support/Herd/bin/":$PATH
