---
- hosts: localhost
  vars:
    source_key: "./id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - name: check .ssh directory exists
      file:
        dest: "{{ lookup('env', 'HOME') }}/.ssh"
        mode: 0700
        state: directory
    - name: install ssh key
      copy:
        src: "{{ source_key }}"
        dest: "{{ dest_key }}"
        mode: 0600
    - name: install public ssh key
      copy:
        src: "{{ source_key }}.pub"
        dest: "{{ dest_key }}.pub"
        mode: 0644
